#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Builds Summa's icon fonts: a subset of Google's Material Symbols Rounded (Apache-2.0).

Downloads the variable font once into ~/.cache/summa, pins two static instances (outlined
FILL=0 and filled FILL=1, weight 400, optical size 24, grade 0), keeps only the icons named in
ICONS (subset by codepoint, not by name: ligatures share letters and would keep everything),
and writes app/src/main/assets/fonts/*.ttf plus the Kotlin table util/Sym.kt.

    python3 tools/icons.py        (needs fonttools: sudo apt install python3-fonttools)
"""
import os
import pathlib
import subprocess
import sys
import urllib.request

from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib import instancer

ICONS = """
add add_circle arrow_back arrow_forward backspace bolt calculate check chevron_left chevron_right close cloud_off
content_copy create_new_folder currency_exchange dark_mode decimal_increase delete delete_forever description dialpad
drag_indicator edit expand_less expand_more file_download file_open file_upload filter_list folder folder_open
format_list_numbered format_size function functions help history info ios_share keep keep_off keyboard
keyboard_return language light_mode link lock menu more_horiz more_vert open_in_full open_in_new palette
picture_in_picture_alt push_pin redo refresh restore_from_trash schedule search settings share sort space_bar
straighten swap_horiz sync tag text_fields tune undo visibility public travel_explore savings flight home work
shopping_cart restaurant receipt_long construction science school fitness_center pets payments bar_chart
contrast format_quote short_text title data_object percent north_east south_west auto_awesome waving_hand
rocket_launch speed timer event calendar_month straighten square_foot thermostat scale water_drop
""".split()

# Symbols also exported as vector drawables (tiles, notifications, launcher icon), from the filled font.
DRAWABLES = ["calculate", "add", "picture_in_picture_alt", "content_copy", "description"]

ROOT = pathlib.Path(__file__).resolve().parent.parent
CACHE = pathlib.Path(os.environ.get("SUMMA_CACHE", pathlib.Path.home() / ".cache/summa"))
BASE = "https://raw.githubusercontent.com/google/material-design-icons/master/variablefont/"
VF = "MaterialSymbolsRounded[FILL,GRAD,opsz,wght]"


def fetch(name):
    path = CACHE / name
    if not path.exists() or path.stat().st_size == 0:
        CACHE.mkdir(parents=True, exist_ok=True)
        url = BASE + urllib.request.quote(name)
        print("downloading", url)
        urllib.request.urlretrieve(url, path)
    return path


def main():
    codepoints = {}
    for line in fetch(VF + ".codepoints").read_text().splitlines():
        name, cp = line.split()
        codepoints[name] = int(cp, 16)
    missing = [n for n in ICONS if n not in codepoints]
    if missing:
        sys.exit(f"not in Material Symbols: {missing}")
    wanted = sorted({codepoints[n] for n in ICONS})
    out_dir = ROOT / "app/src/main/assets/fonts"
    out_dir.mkdir(parents=True, exist_ok=True)
    for fill, suffix in ((0, ""), (1, "_Fill")):
        font = TTFont(fetch(VF + ".ttf"))
        font = instancer.instantiateVariableFont(font, {"FILL": fill, "GRAD": 0, "opsz": 24, "wght": 400})
        options = subset.Options()
        options.layout_features = ["*"]
        options.glyph_names = False
        options.notdef_outline = True
        sub = subset.Subsetter(options)
        sub.populate(unicodes=wanted)
        sub.subset(font)
        target = out_dir / f"MaterialSymbolsRounded{suffix}.ttf"
        font.save(target)
        print(target.relative_to(ROOT), target.stat().st_size, "bytes")

    # Vector drawables: glyph outlines, flipped from font units (y up, 960 per em) to a 0..960 viewport.
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.pens.transformPen import TransformPen
    filled = TTFont(out_dir / "MaterialSymbolsRounded_Fill.ttf")
    cmap, glyphs = filled.getBestCmap(), filled.getGlyphSet()
    res = ROOT / "app/src/main/res/drawable"
    res.mkdir(parents=True, exist_ok=True)
    for n in DRAWABLES:
        pen = SVGPathPen(glyphs)
        glyphs[cmap[codepoints[n]]].draw(TransformPen(pen, (1, 0, 0, -1, 0, 960)))
        (res / f"sym_{n}.xml").write_text(
            '<?xml version="1.0" encoding="utf-8"?>\n'
            '<!-- Material Symbols Rounded "' + n + '" (Apache-2.0, Google), generated by tools/icons.py -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            '    android:width="24dp" android:height="24dp" android:viewportWidth="960" android:viewportHeight="960"\n'
            '    android:tint="?android:attr/colorControlNormal">\n'
            '  <path android:fillColor="@android:color/white" android:pathData="' + pen.getCommands() + '"/>\n'
            '</vector>\n')
        print(f"res/drawable/sym_{n}.xml")

    lines = [
        "package io.github.kuscher.summa.ui",
        "",
        "// Generated by tools/icons.py: Material Symbols Rounded codepoints (Apache-2.0, Google).",
        "// The glyphs live in assets/fonts (outlined + filled); draw them with [SymIcon].",
        "object Sym {",
    ]
    for n in sorted(set(ICONS)):
        lines.append(f'    const val {n.upper()} = "\\u{codepoints[n]:04x}"')
    lines.append("}")
    kt = ROOT / "app/src/main/java/io/github/kuscher/summa/ui/Sym.kt"
    kt.write_text("\n".join(lines) + "\n")
    print(kt.relative_to(ROOT), len(ICONS), "icons")


if __name__ == "__main__":
    main()
