#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Draws Summa's icon: a circle in four quadrants, each a slightly different tangerine, each with
one sign (+ − × ÷) in white. Nothing else. Plain geometry (no fonts). Writes:
  app/src/main/res/drawable/ic_launcher_background.xml   the four quadrants (full bleed; the launcher's mask makes the circle)
  app/src/main/res/drawable/ic_launcher_foreground.xml   the four signs (108 dp canvas)
  app/src/main/res/drawable/ic_launcher_monochrome.xml   themed icon: the signs in one tone
  app/src/main/res/drawable/ic_summa.xml                 24 dp mark (the four signs) for tiles and shortcuts
  docs/images/icon.png, docs/images/icon.svg             README art
    python3 tools/logo.py
"""
import math
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
# Top-left, top-right, bottom-left, bottom-right: one tangerine, stepped a little each way.
QUAD = ["#FF7A31", "#FF8E4D", "#F2661E", "#FF7F3A"]
SIGN = "#FFFFFF"

# On the 108 dp adaptive canvas the visible circle is r = 36 around (54, 54); signs sit at the
# centre of each quadrant, well inside the 66 dp safe zone.
C = 54.0
OFF = 13.2                                       # sign centre offset from the middle
SW = 4.4                                         # stroke width
GS = 5.6                                         # sign half-size

def f(v):
    return f"{v:.3f}".rstrip("0").rstrip(".")


def circle(cx, cy, r, cw=True):
    """A circle path; cw/ccw direction matters only for readers, evenOdd does the holes."""
    s = 1 if cw else 0
    return f"M{f(cx - r)},{f(cy)} a{f(r)},{f(r)} 0 1,{s} {f(2 * r)},0 a{f(r)},{f(r)} 0 1,{s} {f(-2 * r)},0 Z"


def rrect(x, y, w, h, r):
    return (f"M{f(x + r)},{f(y)} h{f(w - 2 * r)} a{f(r)},{f(r)} 0 0 1 {f(r)},{f(r)} v{f(h - 2 * r)} "
            f"a{f(r)},{f(r)} 0 0 1 {f(-r)},{f(r)} h{f(-(w - 2 * r))} a{f(r)},{f(r)} 0 0 1 {f(-r)},{f(-r)} "
            f"v{f(-(h - 2 * r))} a{f(r)},{f(r)} 0 0 1 {f(r)},{f(-r)} Z")


def bar(x1, y1, x2, y2, w):
    """A stroke with round caps as a filled path (a stadium between two points)."""
    ang = math.atan2(y2 - y1, x2 - x1)
    nx, ny = -math.sin(ang) * w / 2, math.cos(ang) * w / 2
    r = w / 2
    return (f"M{f(x1 + nx)},{f(y1 + ny)} L{f(x2 + nx)},{f(y2 + ny)} "
            f"A{f(r)},{f(r)} 0 0 0 {f(x2 - nx)},{f(y2 - ny)} L{f(x1 - nx)},{f(y1 - ny)} "
            f"A{f(r)},{f(r)} 0 0 0 {f(x1 + nx)},{f(y1 + ny)} Z")


def glyph(kind, cx, cy):
    s = GS
    if kind == "+":
        return [bar(cx - s, cy, cx + s, cy, SW), bar(cx, cy - s, cx, cy + s, SW)]
    if kind == "-":
        return [bar(cx - s, cy, cx + s, cy, SW)]
    if kind == "x":
        d = s * 0.78
        return [bar(cx - d, cy - d, cx + d, cy + d, SW), bar(cx - d, cy + d, cx + d, cy - d, SW)]
    # ÷
    return [bar(cx - s, cy, cx + s, cy, SW), circle(cx, cy - s * 0.98, SW * 0.6), circle(cx, cy + s * 0.98, SW * 0.6)]


KEYS = [("+", C - OFF, C - OFF), ("-", C + OFF, C - OFF), ("x", C - OFF, C + OFF), ("/", C + OFF, C + OFF)]


def signs():
    return [path for k, cx, cy in KEYS for path in glyph(k, cx, cy)]


def quadrants():
    return [f"M0,0h54v54h-54z", f"M54,0h54v54h-54z", f"M0,54h54v54h-54z", f"M54,54h54v54h-54z"]


def vector(paths, size=108, viewport=108, extra=""):
    body = "\n".join(paths)
    return ('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/logo.py -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    android:width="{size}dp" android:height="{size}dp"\n'
            f'    android:viewportWidth="{viewport}" android:viewportHeight="{viewport}"{extra}>\n{body}\n</vector>\n')


def p(d, color):
    return f'  <path android:fillColor="{color}" android:pathData="{d}"/>'


def main():
    res = ROOT / "app/src/main/res/drawable"
    res.mkdir(parents=True, exist_ok=True)
    (res / "ic_launcher_background.xml").write_text(vector([p(q, c) for q, c in zip(quadrants(), QUAD)]))
    (res / "ic_launcher_foreground.xml").write_text(vector([p(g, SIGN) for g in signs()]))
    (res / "ic_launcher_monochrome.xml").write_text(vector([p(" ".join(signs()), "#FF000000")]))

    # 24 dp mark: the four signs, scaled up to fill the tile, one tint.
    body = p(" ".join(signs()), "#FFFFFFFF")
    (res / "ic_summa.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/logo.py -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp" android:height="24dp" android:viewportWidth="108" android:viewportHeight="108"\n'
        '    android:tint="?android:attr/colorControlNormal">\n'
        f'  <group android:scaleX="2.2" android:scaleY="2.2" android:pivotX="54" android:pivotY="54">\n{body}\n  </group>\n</vector>\n')

    # README art: the icon through a circle mask.
    docs = ROOT / "docs/images"
    docs.mkdir(parents=True, exist_ok=True)
    quads = "".join(f'<path fill="{c}" d="{q}"/>' for q, c in zip(quadrants(), QUAD))
    glyphs = "".join(f'<path fill="{SIGN}" d="{g}"/>' for g in signs())
    svg = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="18 18 72 72" width="512" height="512">'
           '<defs><clipPath id="c"><circle cx="54" cy="54" r="36"/></clipPath></defs>'
           f'<g clip-path="url(#c)">{quads}{glyphs}</g></svg>')
    (docs / "icon.svg").write_text(svg)
    subprocess.run(["rsvg-convert", "-w", "512", "-h", "512", str(docs / "icon.svg"), "-o", str(docs / "icon.png")], check=True)
    print("icon written")


if __name__ == "__main__":
    main()
