#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Draws Summa's icon: the launcher circle *is* the calculator.

A tangerine body with a cream display (tangerine result bar) and four round ink keys carrying
+ − × ÷. Everything is plain geometry (no fonts). Writes:
  app/src/main/res/drawable/ic_launcher_background.xml   tangerine gradient
  app/src/main/res/drawable/ic_launcher_foreground.xml   display + keys (108 dp canvas)
  app/src/main/res/drawable/ic_launcher_monochrome.xml   themed icon: one tone, glyph holes (evenOdd)
  app/src/main/res/drawable/ic_summa.xml                 24 dp mark for the app header and tiles
  docs/images/icon.png, docs/images/icon.svg             README art
    python3 tools/logo.py
"""
import math
import pathlib
import subprocess

ROOT = pathlib.Path(__file__).resolve().parent.parent
T1, T2 = "#FF7B2C", "#F0520C"      # tangerine gradient
INK, CREAM, BAR = "#1D1A2B", "#FFF4EC", "#F0520C"

# Geometry on the 108 dp adaptive canvas; the 66 dp safe circle is centred on (54, 54), r = 33.
DISP = (37.5, 28.0, 33.0, 12.5)                 # x, y, w, h of the display (fully rounded)
DBAR = (55.0, 34.25, 66.5)                       # result bar: x1, y, x2
KR = 8.7                                         # key radius
KX = (54 - 10.4, 54 + 10.4)
KY = (56.4, 76.0)
SW = 3.2                                         # glyph stroke width
GS = KR * 0.47                                   # glyph half-size


def f(v):
    return f"{v:.3f}".rstrip("0").rstrip(".")


def circle(cx, cy, r, cw=True):
    """A circle path; cw/ccw direction matters only for readers, evenOdd does the holes."""
    s = 1 if cw else 0
    return f"M{f(cx - r)},{f(cy)} a{f(r)},{f(r)} 0 1,{s} {f(2 * r)},0 a{f(r)},{f(r)} 0 1,{s} {f(-2 * r)},0 Z"


def rrect(x, y, w, h, r):
    return (f"M{f(x + r)},{f(y)} h{f(w - 2 * r)} a{f(r)},{f(r)} 0 0 1 {f(r)},{f(r)} v{f(h - 2 * r)} "
            f"a{f(r)},{f(r)} 0 0 1 {f(-r)},{f(r)} h{f(-(w - 2 * r))} a{f(r)},{f(r)} 0 0 1 {f(-r)},{f(-r)} "
            f"v{f(-(h - 2 * r))} a{f(r)},{f(r)} 0 0 1 {f(r)},{f(-r)} Z")


def bar(x1, y1, x2, y2, w):
    """A stroke with round caps as a filled path (a stadium between two points)."""
    ang = math.atan2(y2 - y1, x2 - x1)
    nx, ny = -math.sin(ang) * w / 2, math.cos(ang) * w / 2
    r = w / 2
    return (f"M{f(x1 + nx)},{f(y1 + ny)} L{f(x2 + nx)},{f(y2 + ny)} "
            f"A{f(r)},{f(r)} 0 0 0 {f(x2 - nx)},{f(y2 - ny)} L{f(x1 - nx)},{f(y1 - ny)} "
            f"A{f(r)},{f(r)} 0 0 0 {f(x1 + nx)},{f(y1 + ny)} Z")


def glyph(kind, cx, cy):
    s = GS
    if kind == "+":
        return [bar(cx - s, cy, cx + s, cy, SW), bar(cx, cy - s, cx, cy + s, SW)]
    if kind == "-":
        return [bar(cx - s, cy, cx + s, cy, SW)]
    if kind == "x":
        d = s * 0.78
        return [bar(cx - d, cy - d, cx + d, cy + d, SW), bar(cx - d, cy + d, cx + d, cy - d, SW)]
    # ÷
    return [bar(cx - s, cy, cx + s, cy, SW), circle(cx, cy - s * 0.98, SW * 0.6), circle(cx, cy + s * 0.98, SW * 0.6)]


KEYS = [("+", KX[0], KY[0]), ("-", KX[1], KY[0]), ("x", KX[0], KY[1]), ("/", KX[1], KY[1])]


def parts():
    """(display, display bar, [key circles], [glyph paths])"""
    x, y, w, h = DISP
    disp = rrect(x, y, w, h, h / 2)
    dbar = bar(DBAR[0], DBAR[1], DBAR[2], DBAR[1], 3.6)
    keys = [circle(cx, cy, KR) for _, cx, cy in KEYS]
    glyphs = [p for k, cx, cy in KEYS for p in glyph(k, cx, cy)]
    return disp, dbar, keys, glyphs


def vector(paths, size=108, viewport=108, extra=""):
    body = "\n".join(paths)
    return ('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/logo.py -->\n'
            '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
            f'    android:width="{size}dp" android:height="{size}dp"\n'
            f'    android:viewportWidth="{viewport}" android:viewportHeight="{viewport}"{extra}>\n{body}\n</vector>\n')


def p(d, color, even_odd=False):
    fill = ' android:fillType="evenOdd"' if even_odd else ""
    return f'  <path android:fillColor="{color}"{fill} android:pathData="{d}"/>'


def main():
    disp, dbar, keys, glyphs = parts()
    res = ROOT / "app/src/main/res/drawable"
    res.mkdir(parents=True, exist_ok=True)

    background = ('<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/logo.py -->\n'
                  '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
                  '    xmlns:aapt="http://schemas.android.com/aapt"\n'
                  '    android:width="108dp" android:height="108dp" android:viewportWidth="108" android:viewportHeight="108">\n'
                  '  <path android:pathData="M0,0h108v108h-108z">\n'
                  '    <aapt:attr name="android:fillColor">\n'
                  f'      <gradient android:type="linear" android:startX="18" android:startY="18" android:endX="90" android:endY="90">\n'
                  f'        <item android:offset="0" android:color="#FF{T1[1:]}"/>\n'
                  f'        <item android:offset="1" android:color="#FF{T2[1:]}"/>\n'
                  '      </gradient>\n    </aapt:attr>\n  </path>\n</vector>\n')
    (res / "ic_launcher_background.xml").write_text(background)

    fg = [p(disp, CREAM), p(dbar, BAR)] + [p(k, INK) for k in keys] + [p(g, CREAM) for g in glyphs]
    (res / "ic_launcher_foreground.xml").write_text(vector(fg))

    # Themed icon: display with its bar cut out; keys with their glyphs cut out.
    mono = [p(disp + " " + dbar, "#FF000000", True)]
    for (k, cx, cy), key in zip(KEYS, keys):
        mono.append(p(" ".join([key] + glyph(k, cx, cy)), "#FF000000", True))
    (res / "ic_launcher_monochrome.xml").write_text(vector(mono))

    # 24 dp mark: the same shapes cropped to the safe zone, one tint (for headers and QS tiles).
    mark = [p(disp + " " + dbar, "#FFFFFFFF", True)]
    for (k, cx, cy), key in zip(KEYS, keys):
        mark.append(p(" ".join([key] + glyph(k, cx, cy)), "#FFFFFFFF", True))
    body = "\n".join(mark)
    (res / "ic_summa.xml").write_text(
        '<?xml version="1.0" encoding="utf-8"?>\n<!-- Generated by tools/logo.py -->\n'
        '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
        '    android:width="24dp" android:height="24dp" android:viewportWidth="108" android:viewportHeight="108"\n'
        '    android:tint="?android:attr/colorControlNormal">\n'
        f'  <group android:scaleX="1.5" android:scaleY="1.5" android:pivotX="54" android:pivotY="56">\n{body}\n  </group>\n</vector>\n')

    # README art: the full icon through a circle mask.
    docs = ROOT / "docs/images"
    docs.mkdir(parents=True, exist_ok=True)
    svg_paths = [f'<path fill="{CREAM}" d="{disp}"/>', f'<path fill="{BAR}" d="{dbar}"/>']
    svg_paths += [f'<path fill="{INK}" d="{k}"/>' for k in keys] + [f'<path fill="{CREAM}" d="{g}"/>' for g in glyphs]
    svg = ('<svg xmlns="http://www.w3.org/2000/svg" viewBox="18 18 72 72" width="512" height="512">'
           f'<defs><linearGradient id="t" x1="0" y1="0" x2="1" y2="1"><stop offset="0" stop-color="{T1}"/>'
           f'<stop offset="1" stop-color="{T2}"/></linearGradient><clipPath id="c"><circle cx="54" cy="54" r="36"/></clipPath></defs>'
           f'<g clip-path="url(#c)"><rect width="108" height="108" fill="url(#t)"/>{"".join(svg_paths)}</g></svg>')
    (docs / "icon.svg").write_text(svg)
    subprocess.run(["rsvg-convert", "-w", "512", "-h", "512", str(docs / "icon.svg"), "-o", str(docs / "icon.png")], check=True)
    print("icon written")


if __name__ == "__main__":
    main()
