// SPDX-License-Identifier: MIT
// Generates Summa's brand color schemes with Google's material-color-utilities (Apache-2.0),
// 2025 (Expressive) spec, VIBRANT variant with custom palettes: brand primary, ink-violet
// neutrals, an accent tertiary for units. Writes app/.../ui/theme/Schemes.kt.
//   NODE_PATH=~/.cache/summa/mcu/node_modules node tools/schemes.mjs
import {Hct, DynamicScheme, TonalPalette, Variant, MaterialDynamicColors as M, hexFromArgb, argbFromHex} from '@material/material-color-utilities';
import {writeFileSync} from 'fs';

const roles = ['primary','onPrimary','primaryContainer','onPrimaryContainer','inversePrimary','secondary','onSecondary',
  'secondaryContainer','onSecondaryContainer','tertiary','onTertiary','tertiaryContainer','onTertiaryContainer','background',
  'onBackground','surface','onSurface','surfaceVariant','onSurfaceVariant','surfaceTint','inverseSurface','inverseOnSurface',
  'error','onError','errorContainer','onErrorContainer','outline','outlineVariant','scrim','surfaceBright','surfaceContainer',
  'surfaceContainerHigh','surfaceContainerHighest','surfaceContainerLow','surfaceContainerLowest','surfaceDim',
  'primaryFixed','primaryFixedDim','onPrimaryFixed','onPrimaryFixedVariant','secondaryFixed','secondaryFixedDim',
  'onSecondaryFixed','onSecondaryFixedVariant','tertiaryFixed','tertiaryFixedDim','onTertiaryFixed','onTertiaryFixedVariant'];

const ink = Hct.fromInt(argbFromHex('#2E2946'));
// name: [primary seed, tertiary seed, neutral chroma]
const themes = {
  Tangerine: ['#FF6A00', '#2F5BFF'],
  Cobalt: ['#3D6BFF', '#FFC400'],
  Lime: ['#8BC220', '#FF6A1A'],
  Berry: ['#FF4F86', '#FFB300'],
};
let out = `package io.github.kuscher.summa.ui.theme

// Generated by tools/schemes.mjs (material-color-utilities, 2025 spec). Don't edit by hand.

import androidx.compose.material3.ColorScheme
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

object Schemes {
`;
for (const [name, [p, t]] of Object.entries(themes)) {
  const src = Hct.fromInt(argbFromHex(p)), ter = Hct.fromInt(argbFromHex(t));
  for (const dark of [false, true]) {
    const s = new DynamicScheme({sourceColorHct: src, variant: Variant.VIBRANT, contrastLevel: 0, isDark: dark, specVersion: '2025',
      primaryPalette: TonalPalette.fromHueAndChroma(src.hue, Math.max(src.chroma, 48)),
      secondaryPalette: TonalPalette.fromHueAndChroma(ink.hue, 22),
      tertiaryPalette: TonalPalette.fromHueAndChroma(ter.hue, Math.max(ter.chroma * 0.8, 48)),
      neutralPalette: TonalPalette.fromHueAndChroma(ink.hue, 5),
      neutralVariantPalette: TonalPalette.fromHueAndChroma(ink.hue, 9)});
    const fn = dark ? 'darkColorScheme' : 'lightColorScheme';
    const args = roles.filter(r => M[r]).map(r => `        ${r} = Color(0xFF${hexFromArgb(M[r].getArgb(s)).slice(1).toUpperCase()}),`).join('\n');
    out += `    val ${name.toLowerCase()}${dark ? 'Dark' : 'Light'}: ColorScheme = ${fn}(\n${args}\n    )\n`;
  }
}
out += '}\n';
const target = new URL('../app/src/main/java/io/github/kuscher/summa/ui/theme/Schemes.kt', import.meta.url);
writeFileSync(target, out);
console.log('wrote', target.pathname);
